config/routes.rb
Rails.application.routes.draw do
  resources :warehouses do
    get "stock", on: :member, to: "product_stocks#index"
  end

  resources :suppliers do
    resources :supplier_contacts, path: "contacts"
  end

  resources :products do
    collection do
      post :upload
    end
  end

  namespace :authentication, path: "", as: "" do
    resources :users, only: [ :create, :new ]
    resources :sessions, only: [ :create, :new, :destroy ]
  end

  resources :purchase_orders do
    patch :update_status, on: :member
  end
  resources :order_items, only: [ :index, :new, :create ]

  get "dashboard/index"
  resources :sizes
  resources :product_stocks, except: [ :show ]
  resources :categories, only: [ :new, :create, :index ]
  resources :notifications, only: [ :index ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flash.html.erb
<div data-controller="flash">
  <% if alert || notice %>
    <% color = alert ? 'text-red-400' : 'text-green-400' %>
    <% flash_type = alert ? 'text-red-500 bg-red-50' : 'text-green-500 bg-green-50' %>
    <div class="fixed top-4 right-4 max-w-sm">
      <div class="flex items-center space-x-4 border shadow-lg rounded px-4 py-3 opacity-100 <%= flash_type %>" data-flash-target="flash">
        <div class=" <%= color %>">
          <% if alert %>
            <%= tabler_icon('alert-triangle', size: '25') %>
          <% else %>
            <%= tabler_icon('checkbox', size: '25') %>
          <% end %>
        </div>
        <p>
          <%= alert || notice %>
        </p>
        <button class="inline-flex focus:outline-none focus:text-gray-300 transition ease-in-out duration-150" data-action="click->flash#close">
        </button>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="bg-white w-full border border-gray-200 shadow-sm">
  <%= tabler_icon('bell', size: '15') %>
  <div class="border-red-400 rounded-full bg-red-100 text-red-500 text-xs font-semibold px-2 py-1 flex items-center justify-center w-6 h-6">
    <%= tabler_icon('bell', size: '15') %>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<aside class="sidebar">
  <nav class="w-64 h-full border border-gray-200 shadow-lg flex flex-col justify-between">
    <div>
      <div class="flex items-center space-x-5 my-3">
        <%= tabler_icon('rocket', size: '35') %>
        <h1 class="text-2xl py-2 text-black font-bold hidden md:block">Nvex</h1>
      </div>
      <ul class="space-y-10">
        <li>
          <%= link_to dashboard_index_path, class: "flex items-center space-x-3 text-sm rounded-sm p-2 #{current_page?(dashboard_index_path) ? 'font-semibold border-r-5 border-[#7C5BF3]' : 'text-gray-400 hover:bg-gray-200 hover:rounded-lg'}" do %>
            <%= tabler_icon('home-2', size: '20', class: "#{current_page?(dashboard_index_path) ? 'text-[#7C5BF3]' : 'text-gray-400'}") %>
            <span> Dashboard </span>
          <% end %>
        </li>
        <li>
          <%= link_to products_path, class: "flex items-center space-x-3 text-sm rounded-sm p-2 #{current_page?(products_path) ? 'font-semibold border-r-5 border-[#7C5BF3]' : 'text-gray-400 hover:bg-gray-200 hover:rounded-lg'}" do %>
            <%= tabler_icon('cube', size: '20', class: "#{current_page?(products_path) ? 'text-[#7C5BF3]' : 'text-gray-400'}") %>
            <span> Products </span>
          <% end %>
        </li>
        <li>
          <%= link_to notifications_path, class: "flex items-center space-x-3 text-sm rounded-sm p-2 #{current_page?(notifications_path) ? 'font-semibold border-r-5 border-[#7C5BF3]' : 'text-gray-400 hover:bg-gray-200 hover:rounded-lg'}" do %>
            <%= tabler_icon('bell', size: '20', class: "#{current_page?(notifications_path) ? 'text-[#7C5BF3]' : 'text-gray-400'}") %>
            <span> Notifications </span>
          <% end %>
        </li>
        <li>
          <%= link_to suppliers_path, class: "flex items-center space-x-3 text-sm rounded-sm p-2 #{current_page?(suppliers_path) ? 'font-semibold border-r-5 border-[#7C5BF3]' : 'text-gray-400 hover:bg-gray-200 hover:rounded-lg'}" do %>
            <%= tabler_icon('users-group', size: '20', class: "#{current_page?(suppliers_path) ? 'text-[#7C5BF3]' : 'text-gray-400'}") %>
            <span> Suppliers </span>
          <% end %>
        </li>
        <li>
          <%= link_to warehouses_path, class: "flex items-center space-x-3 text-sm rounded-sm p-2 #{current_page?(warehouses_path) ? 'font-semibold border-r-5 border-[#7C5BF3]' : 'text-gray-400 hover:bg-gray-200 hover:rounded-lg'}" do %>
            <%= tabler_icon('building-warehouse', size: '20', class: "#{current_page?(warehouses_path) ? 'text-[#7C5BF3]' : 'text-gray-400'}") %>
            <span> Warehouses </span>
          <% end %>
        </li>
        <li>
          <%= link_to purchase_orders_path, class: "flex items-center space-x-3 text-sm rounded-sm p-2 #{current_page?(purchase_orders_path) ? 'font-semibold border-r-5 border-[#7C5BF3]' : 'text-gray-400 hover:bg-gray-200 hover:rounded-lg'}" do %>
            <%= tabler_icon('truck-delivery', size: '20', class: "#{current_page?(purchase_orders_path) ? 'text-[#7C5BF3]' : 'text-gray-400'}") %>
            <span> Purchase orders </span>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="p-2">
      <%= link_to session_path(Current.user.id), data: { turbo_method: :delete, turbo_confirm: 'Are you sure' } ,class: "flex items-center space-x-3 text-sm text-white rounded-lg p-3 bg-[#FFA766] hover:bg-[#FF8A33]" do %>
        <%= tabler_icon('logout', size: '20', color: "#ffffff") %>
        <span> Logout </span>
      <% end %>
    </div>
  </nav>
</aside>

app/views/shared/_step_indicator.html.erb
<% steps = ["Create order", "Add products"] %>

<div class="w-96 flex items-center justify-between mx-auto space-x-4">
  <% steps.each_with_index do |step_name, index| %>
    <% step_number = index + 1 %>

    <div class="relative flex flex-col items-center">
      <div class="flex h-10 w-10 items-center justify-center rounded-full border-2 <%= step_classes(step_number, @current_step) %>">
        <%= step_number < @current_step ? tabler_icon('check', size: '20') : step_number %>
      </div>
      <div class="mt-2 text-sm font-medium <%= step_number <= @current_step ? 'text-gray-900' : 'text-gray-400' %>">
        <%= step_name %>
      </div>
    </div>

    <% unless step_number == steps.length %>
      <div class="flex-1 h-0.5 bg-gray-300 relative">
        <div class="absolute top-0 left-0 h-full <%= step_number < @current_step ? 'bg-green-500' : 'bg-gray-300' %> w-full"></div>
      </div>
    <% end %>
  <% end %>
</div>