config/routes.rb
Rails.application.routes.draw do
  resources :warehouses do
    get "stock", on: :member, to: "product_stocks#index"
  end

  resources :suppliers do
    resources :supplier_contacts, path: "contacts"
  end

  resources :products do
    collection do
      post :upload
    end
  end

  namespace :authentication, path: "", as: "" do
    resources :users, only: [ :create, :new ]
    resources :sessions, only: [ :create, :new, :destroy ]
  end

  resources :purchase_orders do
    patch :update_status, on: :member
  end
  resources :order_items, only: [ :index, :new, :create ]

  get "dashboard/index"
  resources :sizes
  resources :product_stocks, except: [ :show ]
  resources :categories, only: [ :new, :create, :index ]
  resources :notifications, only: [ :index ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/product.rb
require 'csv'

class Product < ApplicationRecord
  include PgSearch::Model

  has_many :product_sizes, dependent: :destroy
  has_many :sizes, through: :product_sizes
  has_many :order_items, dependent: :destroy
  has_many :purchase_orders, through: :order_items
  belongs_to :category
  belongs_to :user, default: -> { Current.user }
  has_one :product_stock, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :category_id, presence: true

  pg_search_scope :search_full_text, against: {
    name: 'A',
  }

  scope :total_products_price, -> { sum(:price) }
  scope :order_by_date, -> { order(created_at: :desc) }
  scope :for_user, ->(user) { where(user_id: user.id) }


  def self.to_csv
    products = all.includes(:category)
    CSV.generate(headers: true) do |csv|
      headers = column_names - ['category_id'] + ['category_name']
      csv << headers
      products.each do |product|
        values = product.attributes.except('category_id').values
        values << product.category&.name
        csv << values
      end
    end
  end
end

app/controllers/products_controller.rb
require "csv"

class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :set_sizes, only: %i[ new create edit update ]
  layout 'product'
  # GET /products or /products.json
  def index
    @pagy, @products = pagy(Product.includes(:category, :product_stock).for_user(Current.user).order_by_date)
    @button = "focus:outline-none text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900"
    respond_to do |format|
      format.html
      format.csv { send_data Product.to_csv, filename: "products-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv" }
    end

    if params[:query_text].present?
      @products = Product.search_full_text(params[:query_text])
    end
    if params[:category_id].present?
      @products = Product.where(category_id: params[:category_id])
    end
    if params[:stock_min].present?
      @products = Product.joins(:product_stock).where("product_stocks.quantity >= ?", params[:stock_min])
    end
    if params[:price_min].present?
      @products = Product.where("price >= ?", params[:price_min])
    end
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product was successfully created."
      # redirect_to products_path, notice: "Product was successfullyk created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    if @product.update(product_params)
      redirect_to @product, notice: "Product was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!
    redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed."
  end

  def upload
    uploaded_file = params[:csv_file]
    if uploaded_file.present?
      begin
        csv_data = CSV.parse(uploaded_file.read, headers: true)
        csv_data.each do |row|
          # Process each row of the CSV file
          Product.create!(name: row["name"], description: row["description"], price: row["price"], category_id: row["category_id"], created_at: row["created_at"], updated_at: row["updated_at"])
          redirect_to products_path, notice: "Productos importados correctamente"
          return
        end
      rescue  CSV::MalformedCSVError
        redirect_to products_path, alert: "El archivo no tiene el formato correcto"
      end
    else
      redirect_to products_path, alert: "Debes subir un archivo CSV"
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params.expect(:id))
  end

  def set_sizes
    @sizes = Size.all
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.expect(product: [:name, :description, :price, :category_id, size_ids: []])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, class: "contents", data: { controller: "sizes-fields" }) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul class="list-disc ml-6">
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, class: "block text-sm font-medium text-gray-700 mb-1" %>
    <div class="mt-1 relative rounded-md shadow-sm">
      <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
        <%= tabler_icon('package', size: '15', class: "text-[#7C5BF3]") %>
      </div>
      <%= form.text_field :name, class: ["block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md focus:ring-indigo-500 focus:border-indigo-500", { "border-gray-400 focus:outline-blue-600": product.errors[:name].none?, "border-red-400 focus:outline-red-600": product.errors[:name].any? }] %>
    </div>
  </div>

  <div class="my-3">
    <%= form.label :description, class: "block text-sm font-medium text-gray-700 mb-1" %>
    <div class="mt-1 relative rounded-md shadow-sm">
      <%= form.textarea :description, rows: 4, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full focus:ring-indigo-500 focus:border-indigo-500", { "border-gray-400 focus:outline-blue-600": product.errors[:description].none?, "border-red-400 focus:outline-red-600": product.errors[:description].any? }] %>
    </div>
  </div>

  <div class="my-5">
    <%= form.label :price, class: "block text-sm font-medium text-gray-700 mb-1" %>
    <div class="mt-1 relative rounded-md shadow-sm">
      <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
        <%= tabler_icon('currency-dollar', size: '15', class: "text-[#7C5BF3]") %>
      </div>
      <%= form.text_field :price, class: ["block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md focus:ring-indigo-500 focus:border-indigo-500", { "border-gray-400 focus:outline-blue-600": product.errors[:price].none?, "border-red-400 focus:outline-red-600": product.errors[:price].any? }] %>
    </div>
  </div>

  <div class="my-5">
    <%= form.label :category_id, for: 'floating_category_id', class: "block text-sm font-medium text-gray-700 mb-1" %>
    <div class="mt-1 relative rounded-md shadow-sm">
      <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
        <%= tabler_icon('tag', size: '15', class: "text-[#7C5BF3]") %>
      </div>
      <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Select a category" }, { id: 'floating_category_id', class: "block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md focus:ring-indigo-500 focus:border-indigo-500" } %>
    </div>
  </div>


  <div class="flex flex-col p-4 rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300">
    <label class="inline-flex items-center cursor-pointer my-2">
      <div class="relative">
        <%= form.check_box :activate_sizes, class: "sr-only peer", data: { action: "sizes-fields#toggleMinStock" } %>
        <div class="w-11 h-6 bg-gray-200 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-green-500"></div>
      </div>
      <%= form.label :activate_sizes, "¿Does your products have sizes?", class: "ml-3 text-sm font-medium text-black" %>
    </label>

    <div class="flex flex-wrap gap-4 mt-2 hidden" data-sizes-fields-target="sizes">
      <%= form.collection_check_boxes :size_ids, @sizes, :id, :name, include_hidden: false do |b| %>
        <div class="flex items-center">
          <%= b.check_box(class: "hidden peer") %>
          <%= b.label(class: "flex items-center space-x-2 cursor-pointer text-sm text-gray-600 peer-checked:text-blue-500 peer-checked:font-semibold") do %>
      <span class="w-6 h-6 border border-gray-300 rounded flex items-center justify-center text-center bg-white peer-checked:bg-blue-100">
        <%= b.object.name %>
      </span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="mt-4">
    <%= form.submit class: "flex items-center text-white bg-[#7C5BF3] hover:bg-[#9576F5] rounded-lg p-3" %>
  </div>

<% end %>

app/views/products/_navigation.html.erb
<nav class="flex justify-end items-center mb-6">
  <div class="flex items-center space-x-2">
    <%= form_with url: upload_products_path, multipart: true, data: { controller: "file-upload" } do |form| %>
      <div class="flex items-center space-x-2">
        <label class="flex items-center text-black shadow-lg rounded-lg p-3">
          <%= tabler_icon('upload', size: '20', class: "mr-2") %>
          Importar productos
          <%= file_field_tag :csv_file, accept: ".csv", class: "hidden", id: "csv_file_input", data: { file_upload_target: "input", action: "change->file-upload#toggleButton" } %>
        </label>
        <%= form.button class: "flex items-center text-white bg-[#7C5BF3] hover:bg-[#9576F5] rounded-lg p-3 hidden", data: { file_upload_target: "submit" } do %>
          <%= tabler_icon('upload', size: '20', class: "mr-2") %>
          <span>Subir</span>
        <% end %>
      </div>
    <% end %>
    <%= link_to products_path(format: :csv), class: "flex items-center text-white bg-[#7C5BF3] hover:bg-[#9576F5] rounded-lg p-3" do %>
      <%= tabler_icon('file-type-csv', size: '20', class: "mr-2") %>
      Generar CSV
    <% end %>
    <%= link_to new_product_stock_path, class: 'flex items-center text-white bg-[#7C5BF3] hover:bg-[#9576F5] rounded-lg p-3' do %>
      <%= tabler_icon('stack-3', size: '20', class: "mr-2") %>
      Agregar stock
    <% end %>
    <%= link_to new_product_path, class: 'flex items-center text-white bg-[#7C5BF3] hover:bg-[#9576F5] rounded-lg p-3' do %>
      <%= tabler_icon('plus', size: '20', class: "mr-2") %>
      Agregar producto
    <% end %>
  </div>
</nav>

<nav>
  <%= form_with url: products_path, method: :get do |form| %>
    <div class="flex justify-between items-center space-x-4">
      <div class="relative w-64">
        <%= form.text_field :query_text, placeholder: 'Search', onChange: 'this.form.requestSubmit()', value: params[:query_text], class: "w-full py-2 pl-10 pr-4 text-gray-700 bg-white border rounded-full focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-colors duration-300" %>
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <%= tabler_icon('search', size: '20', class: "mr-2") %>
        </div>
      </div>
      <div class="relative w-64">
        <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: 'Select a category', include_blank: true }, { onChange: 'this.form.requestSubmit()', class: "w-full py-2 pl-10 pr-4 text-gray-700 bg-white border rounded-full focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-colors duration-300" } %>
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <%= tabler_icon('category', size: '20', class: "mr-2") %>
        </div>
      </div>
      <div class="relative w-64">
        <%= form.text_field :stock_min, placeholder: 'Stock min', onChange: 'this.form.requestSubmit()', value: params[:stock_min], class: "w-full py-2 pl-10 pr-4 text-gray-700 bg-white border rounded-full focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-colors duration-300" %>
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <%= tabler_icon('stack-3', size: '20', class: "mr-2") %>
        </div>
      </div>
      <div class="relative w-64">
        <%= form.text_field :price_min, placeholder: 'Price min', onChange: 'this.form.requestSubmit()', value: params[:price_min], class: "w-full py-2 pl-10 pr-4 text-gray-700 bg-white border rounded-full focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-colors duration-300" %>
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <%= tabler_icon('currency-dollar', size: '20', class: "mr-2") %>
        </div>
      </div>
    </div>
  <% end %>
</nav>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <tr class="bg-white border-b hover:bg-gray-200">
    <td class="flex px-6 py-4 whitespace-nowrap">
      <%= link_to product_path(product),
                  class: "flex px-2 py-1 whitespace-nowrap text-sm font-medium text-indigo-600 hover:text-indigo-800 hover:underline transition duration-200 cursor-pointer" do %>
        <%= tabler_icon('box', size: '20', class: 'text-indigo-600 mr-2') %>
        <%= product.name %>
      <% end %>
    </td>
    <td class="px-6 py-4 whitespace-nowrap">
      <p class="text-sm font-medium text-gray-900">
        <%= number_to_currency(product.price) %>
      </p>
    </td>
    <td class="px-6 py-4 whitespace-nowrap">
      <%#= products.product_stock.quantity %>
      <p class="text-sm font-medium text-gray-900">
        <%= product.product_stock&.quantity || "Sin stock" %>
      </p>
    </td>
    <td class="px-6 py-4 whitespace-nowrap">
      <span class="<%= category_color(product.category.name) %> px-2 py-1 rounded-full text-xs">
        <%= product.category.name %>
      </span>
    </td>
    <td class="flex justify-center whitespace-nowrap space-x-2 text-right text-sm font-medium">
      <%= link_to edit_product_path(product), class: "flex items-center text-white bg-[#7C5BF3] hover:bg-[#9576F5] rounded-lg p-2 " do %>
        <%= tabler_icon('edit', size: '20', class: "mr-2") %>
        Edit
      <% end %>
      <%= button_to product, method: :delete, class: 'flex items-center text-white bg-red-400 hover:bg-red-500 rounded-lg p-2' do %>
        <%= tabler_icon('trash', size: '20', class: "mr-2") %>
        Delete
      <% end %>
    </td>
  </tr>
</div>

app/views/products/_summary.html.erb
<section aria-label="Resumen del inventario" class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
  <article class="bg-blue-100 p-4 rounded-lg">
    <h2 class="text-lg font-semibold mb-2">Total de Productos</h2>
    <p class="text-3xl font-bold"><%= @products.count %></p>
  </article>
  <article class="bg-green-100 p-4 rounded-lg">
    <h2 class="text-lg font-semibold mb-2">Total de Artículos</h2>
    <p class="text-3xl font-bold"><%= number_with_delimiter(@total_stock) %></p>
  </article>
  <article class="bg-yellow-100 p-4 rounded-lg">
    <h2 class="text-lg font-semibold mb-2">Valor Total del Inventario</h2>
    <p class="text-3xl font-bold"><%= number_to_currency(@total_products_price) %></p>
  </article>
</section>

app/views/products/edit.html.erb
<% content_for :title, "Editing products" %>

<div class="p-3 h-full w-[50%]">
  <%= render "form", product: @product %>
</div>

app/views/products/index.html.erb
<% content_for :title, "Products" %>
<main class="container mx-auto p-3 h-full overflow-y-auto scrollbar-hide">
  <%= render "products/components/navigation" %>
  <%= render "products/components/filters" %>
  <section class="mt-3 relative overflow-x-auto">
    <table class="min-w-full divide-y divide-gray-200 rounded-lg overflow-hidden">
      <thead class="bg-gray-50">
      <tr>
        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
          Name
        </th>
        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
          Price
        </th>
        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
          Stock
        </th>
        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
          Category
        </th>
        <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
          Actions
        </th>
      </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        <%= render partial: 'product', collection: @products, cached: true %>
      </tbody>
    </table>
  </section>
  <%== pagy_nav(@pagy) %>
</main>

app/views/products/new.html.erb
<% content_for :title, "New products" %>

<%= turbo_frame_tag "modal" do %>
  <div data-controller="modal">
    <div data-action="click->modal#close" class="fixed z-10 w-full h-full top-0 left-0 bg-black opacity-40"></div>
    <div data-modal-target="sidebar" class="fixed top-0 right-0 z-20 w-1/2 sm:w-3/6 lg:w-2/6 h-full bg-white shadow rounded-sm flex flex-col ease-in-out duration-300 translate-x-full">
      <div class="flex items-center justify-between p-4 border-b border-gray-200 text-black">
        <h1 class="font-bold text-lg">New product</h1>
        <button type="button" data-action="click->modal#close"
                class="p-2 rounded-full bg-gray-200 hover:bg-gray-300 transition duration-200">
          <%= tabler_icon "x", size: 15, class: "text-gray-600 hover:text-gray-800" %>
        </button>
      </div>
      <div class="flex-1 overflow-y-auto p-5 bg-white scrollbar-hide">
        <%= render "form", product: @product %>
      </div>

    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<% content_for :title, "Showing products" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing product</h1>

  <%= render @product %>

  <%= link_to "Edit this products", edit_product_path(@product), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to products", products_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this products", @product, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>