config/routes.rb
Rails.application.routes.draw do
  resources :warehouses do
    get "stock", on: :member, to: "product_stocks#index"
  end

  resources :suppliers do
    resources :supplier_contacts, path: "contacts"
  end

  resources :products do
    collection do
      post :upload
    end
  end

  namespace :authentication, path: "", as: "" do
    resources :users, only: [ :create, :new ]
    resources :sessions, only: [ :create, :new, :destroy ]
  end

  resources :purchase_orders do
    patch :update_status, on: :member
  end
  resources :order_items, only: [ :index, :new, :create ]

  get "dashboard/index"
  resources :sizes
  resources :product_stocks, except: [ :show ]
  resources :categories, only: [ :new, :create, :index ]
  resources :notifications, only: [ :index ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/supplier_contact.rb
class SupplierContact < ApplicationRecord
  belongs_to :supplier

  validates :name, presence: true, length: { minimum: 3 }, format: {
    with: /\A[a-zA-Z\s]+\z/,
    message: :invalid
  }
  validates :last_name, presence: true, length: { minimum: 3 }, format: {
    with: /\A[a-zA-Z\s]+\z/,
    message: :invalid
  }
  validates :email, presence: true, uniqueness: true, format: {
    with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
    message: :invalid
  }
  validates :phone, presence: true
  validates :supplier_id, presence: true
  scope :ordered, -> { order(id: :desc) }
end

app/controllers/supplier_contacts_controller.rb
class SupplierContactsController < ApplicationController
  before_action :set_supplier
  before_action :set_supplier_contact, only: %i[ edit update destroy ]

  # GET /supplier_contacts or /supplier_contacts.json
  def index
    @supplier_contacts = SupplierContact.all
  end

  # GET /supplier_contacts/new
  def new
    @supplier_contact ||= SupplierContact.new
  end

  # GET /supplier_contacts/1/edit
  def edit
  end

  # POST /supplier_contacts or /supplier_contacts.json
  def create
    @supplier_contact = SupplierContact.new(supplier_contact_params)
    @supplier_contact.supplier_id = @supplier.id
    if @supplier_contact.save
      respond_to do |format|
        format.html { redirect_to supplier_path(@supplier_contact.supplier), notice: "Supplier contact was successfully created." }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /supplier_contacts/1 or /supplier_contacts/1.json
  def update
    if @supplier_contact.update(supplier_contact_params)
      redirect_to supplier_path(@supplier_contact.supplier), notice: "Supplier contact was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /supplier_contacts/1 or /supplier_contacts/1.json
  def destroy
    @supplier_contact.destroy!
    respond_to do |format|
      format.html { redirect_to supplier_path(@supplier_contact.supplier), notice: "Supplier contact was successfully destroyed." }
      format.turbo_stream
    end
  end

  private

  def set_supplier
    @supplier = Supplier.find(params[:supplier_id])
  end
  def set_supplier_contact
    @supplier_contact = SupplierContact.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def supplier_contact_params
    params.expect(supplier_contact: [:name, :last_name, :email, :phone, :supplier_id])
  end
end

app/helpers/supplier_contacts_helper.rb
module SupplierContactsHelper

end

app/views/supplier_contacts/_form.html.erb
<%= form_with(model: [@supplier, @supplier_contact], class: "contents", data: { controller: "contact-form"}) do |form| %>
  <div class="max-w-4xl mx-auto p-8">
    <% if supplier_contact.errors.any? %>
      <div id="error_explanation" class="flex items-start bg-red-50 text-red-600 px-4 py-3 mb-4 rounded-md border border-red-300" data-contact-form-target="error">
        <div class="flex-shrink-0">
          <%= tabler_icon('alert-circle', size: '20', class: "text-red-600 mr-3") %>
        </div>
        <div>
          <h2 class="font-semibold"><%= pluralize(supplier_contact.errors.count, "error") %> prohibited this contact
            from being saved:</h2>
          <ul class="list-disc ml-6 text-sm">
            <% supplier_contact.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    <div class="flex items-center space-x-2">
      <div class="flex-1 relative">
        <div class="relative border <%= supplier_contact.errors[:name].any? ? 'border-red-400' : 'border-gray-700' %> rounded-md focus-within:border-gray-500">
          <%= form.label :name, class: "absolute -top-2 left-2 -mt-px px-1 bg-white text-xs font-medium text-gray-500" %>
          <div class="absolute inset-y-0 left-3 flex items-center pointer-events-none">
            <%= tabler_icon('user', size: '20') %>
          </div>
          <%= form.text_field :name, placeholder: "Xavier", class: ["block w-full bg-transparent border-0 pl-10 pr-3 py-2 text-black placeholder-gray-600 focus:outline-none focus:ring-0 sm:text-sm"] %>
        </div>
      </div>

      <div class="flex-1 relative">
        <div class="relative border <%= supplier_contact.errors[:last_name].any? ? 'border-red-400' : 'border-gray-700' %> rounded-md focus-within:border-gray-500">
          <%= form.label :last_name, class: "absolute -top-2 left-2 -mt-px px-1 bg-white text-xs font-medium text-gray-500" %>
          <div class="absolute inset-y-0 left-3 flex items-center pointer-events-none">
            <%= tabler_icon('user', size: '20') %>
          </div>
          <%= form.text_field :last_name, placeholder: "Caballero Zanabria", class: ["block w-full bg-transparent border-0 pl-10 pr-3 py-2 text-black placeholder-gray-600 focus:outline-none focus:ring-0 sm:text-sm", { "border-gray-400 focus:outline-blue-600": supplier_contact.errors[:last_name].none?, "border-red-400 focus:outline-red-600": supplier_contact.errors[:last_name].any? }] %>
        </div>
      </div>

      <div class="flex-1 relative">
        <div class="relative border <%= supplier_contact.errors[:email].any? ? 'border-red-400' : 'border-gray-700' %> rounded-md focus-within:border-gray-500">
          <%= form.label :email, class: "absolute -top-2 left-2 -mt-px px-1 bg-white text-xs font-medium text-gray-500" %>
          <div class="absolute inset-y-0 left-3 flex items-center pointer-events-none">
            <%= tabler_icon('mail', size: '20') %>
          </div>
          <%= form.text_field :email, placeholder: "example@gmail.com", class: ["block w-full bg-transparent border-0 pl-10 pr-3 py-2 text-black placeholder-gray-600 focus:outline-none focus:ring-0 sm:text-sm", { "border-gray-400 focus:outline-blue-600": supplier_contact.errors[:email].none?, "border-red-400 focus:outline-red-600": supplier_contact.errors[:email].any? }] %>
        </div>
      </div>

      <div class="flex-1 relative">
        <div class="relative border <%= supplier_contact.errors[:phone].any? ? 'border-red-400' : 'border-gray-700' %> rounded-md focus-within:border-gray-500">
          <%= form.label :phone, class: "absolute -top-2 left-2 -mt-px px-1 bg-white text-xs font-medium text-gray-500" %>
          <div class="absolute inset-y-0 left-3 flex items-center pointer-events-none">
            <%= tabler_icon('user', size: '20') %>
          </div>
          <%= form.text_field :phone, placeholder: "3312695478", class: ["block w-full bg-transparent border-0 pl-10 pr-3 py-2 text-black placeholder-gray-600 focus:outline-none focus:ring-0 sm:text-sm", { "border-gray-400 focus:outline-blue-600": supplier_contact.errors[:phone].none?, "border-red-400 focus:outline-red-600": supplier_contact.errors[:phone].any? }] %>
        </div>
      </div>

      <div>
        <%= form.submit class: "rounded-md px-2.5 py-1.5 bg-[#7C5BF3] hover:bg-[#9576F5] text-white inline-block font-medium cursor-pointer" %>
      </div>

    </div>
<% end %>
</div>

app/views/supplier_contacts/_supplier_contact.html.erb
<div id="<%= dom_id supplier_contact %>">
  <article class="flex items-center p-4 rounded-lg transition-shadow duration-300">
    <%= user_avatar(supplier_contact.name) %>
    <div class="flex w-full items-center justify-between p-2">
      <section class="flex items-center gap-4 text-gray-600">
        <header>
          <h3 class="font-semibold text-gray-800"><%= supplier_contact.name %></h3>
        </header>
        <div class="flex items-center">
          <%= tabler_icon('mail', size: '20', class: "mr-2") %>
          <span><%= supplier_contact.email %></span>
        </div>
        <div class="flex items-center">
          <%= tabler_icon('phone', size: '20', class: "mr-2") %>
          <span><%= supplier_contact.phone %></span>
        </div>
      </section>
      <div class="flex space-x-2 mt-2">
        <%= link_to edit_supplier_supplier_contact_path(@supplier, supplier_contact), class: 'flex items-center text-white bg-[#7C5BF3] hover:bg-[#9576F5] rounded-lg p-2' do %>
          <%= tabler_icon('edit', size: '20', class: "mr-2") %>
          Edit
        <% end %>
        <%= button_to supplier_supplier_contact_path(@supplier, supplier_contact), method: :delete, class: 'flex items-center text-white bg-red-400 hover:bg-red-500 rounded-lg p-2' do %>
          <%= tabler_icon('trash', size: '20', class: "mr-2") %>
          Delete
        <% end %>
      </div>
    </div>
  </article>
  <hr class="my-3 border-gray-200">
</div>

app/views/supplier_contacts/create.turbo_stream.erb
<%= turbo_stream.prepend "supplier_contacts", partial: "supplier_contacts/supplier_contact", locals: { supplier_contact: @supplier_contact } %>
<%= turbo_stream.update SupplierContact.new, "" %>

app/views/supplier_contacts/destroy.turbo_stream.erb
<%= turbo_stream.remove "supplier_contact_#{@supplier_contact.id}" %>

app/views/supplier_contacts/edit.html.erb
<% content_for :title, "Editing supplier contact" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing supplier contact</h1>

  <%= turbo_frame_tag @supplier_contact do %>
    <%= render "form", supplier_contact: @supplier_contact %>
  <% end %>

  <%= link_to "Show this supplier contact", supplier_supplier_contact_path(@supplier, @supplier_contact), class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to supplier contacts", supplier_supplier_contacts_path(@supplier), class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/supplier_contacts/index.html.erb
<% content_for :title, "Supplier contacts" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Supplier contacts</h1>
    <%= link_to "New supplier contact", new_supplier_supplier_contact_path(supplier_id: @supplier.id), class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="supplier_contacts" class="min-w-full">
    <% if @supplier_contacts.any? %>
      <% @supplier_contacts.each do |supplier_contact| %>
        <%= render supplier_contact %>
      <% end %>
    <% else %>
      <p class="text-center my-10">No supplier contacts found.</p>
    <% end %>
  </div>
</div>

app/views/supplier_contacts/new.html.erb
<% content_for :title, "New supplier contact" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New supplier contact</h1>
  <%= turbo_frame_tag @supplier_contact do %>
    <%= render "form", supplier_contact: @supplier_contact %>
  <% end %>
  <%= link_to "Back to supplier contacts", supplier_supplier_contacts_path(@supplier), class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>